<cfcomponent output="false">
  <cffunction name="throwCFCFault" returntype="String">
    <cfthrow message="An error message generated by a CFC function" 
      errorcode="CFC Function Error">
    <cfreturn "A String">
  </cffunction>
</cfcomponent>